### ISSUE TITLE
Feature: Better defaults for label texts

### ISSUE THREAD

**Issue by yGuy** [yWorks/yfiles-jupyter-graphs-for-neo4j#2]
I think the simple logic that the neo4j browser is using is something that we should also apply to label texts, by default,

If there is a property called "Title"/"title"/"Name"/"name" use the value as label text when the user did not specify a custom binding. otherwise use the neo4j label as the label text.

Currently you always need to hover to find out what item you have and for many queries all the nodes will have the same text labels.

**Comment by fskpf** [comment]
We could also address this directly in the [yfiles-jupyter-graphs](https://github.com/yWorks/yfiles-jupyter-graphs) widget.

Similar to the default node/relationship color mapping, we could provide another default label mapping for neo4j graph imports that uses common keywords for labels and falls back to the item type otherwise.
