### ISSUE TITLE
Could this work on a kuzu database?

### ISSUE THREAD

**Issue by Analect** [yWorks/yfiles-jupyter-graphs-for-neo4j#8]
Thanks for creating this. I'm using kuzu, an embedded graph database, which has compatability with cypher, (per https://docs.kuzudb.com/get-started/cypher-intro/). I was wondering if this widget could therefore work to connect with a kuzu db rather than a neo4j one?

If so, I'm keen to try to use quarto-live to perhaps run this leveraging pyodide, per this: https://r-wasm.github.io/quarto-live/ ... which would hopefully dispense with the need for a running jupyter notebook. Packages, such as yours, would get installed per here: https://r-wasm.github.io/quarto-live/getting_started/packages.html

**Comment by Analect** [comment]
You had previously shown this approach on your yfiles-jupyter-graphs widget here: https://github.com/yWorks/yfiles-jupyter-graphs/discussions/41 that leverages networkx, which appears to work for this widget too. 

```
from yfiles_jupyter_graphs_for_neo4j import Neo4jGraphWidget
from google.colab import output
output.enable_custom_widget_manager()
result = conn.execute('MATCH (a:User) - [f:Follows] -> (b:User) RETURN a,f,b')
GraphWidget(graph = result.get_as_networkx())
```

![image](https://github.com/user-attachments/assets/248293bd-00db-4cb9-9728-87f864f326e6)

I can see there is a `add_node_configuration` setting, but perhaps this is dependent on accessing the neo4j driver? I note from this example, https://colab.research.google.com/github/yWorks/yfiles-jupyter-graphs-for-neo4j/blob/main/examples/feature_example.ipynb, that a default config for nodes and relationships gets applied, which makes the graph much more visually appealing versus the one I'm currently getting above.

![image](https://github.com/user-attachments/assets/c77dbe33-c904-492d-a525-3edaa83c16a4)


Is there a way to adjust the configuration using this `get_as_networkx()` approach? Thanks.

**Comment by fskpf** [comment]
Loading the networkx graph does not work with `yfiles-jupyter-graphs-for-neo4j` because this is tailored for Neo4j graphs and has no API to load a different graph. Instead use the (generic) `yfiles-jupyter-graphs` widget.

Your snippet above actually uses the `yfiles-jupyter-graphs` widget. Note how you import the `Neo4jGraphWidget` but use the `GraphWidget` instead:
```python
from yfiles_jupyter_graphs_for_neo4j import Neo4jGraphWidget
# ....
GraphWidget(graph = result.get_as_networkx())
```

That said, `Neo4jGraphWidget` just wraps the `GraphWidget` and provides a tailored API. Anything that you see with the `Neo4jGraphWidget` can be implemented based on the generic `GraphWidget`. Internally, it merely creates a `GraphWidget` with specific node/relationship mappings given by the user, as you can see in its [source code](https://github.com/yWorks/yfiles-jupyter-graphs-for-neo4j/blob/main/src/yfiles_jupyter_graphs_for_neo4j/Yfiles_Neo4j_Graphs.py).

The default color mapping is a feature for Neo4j graph imports of the core `GraphWidget`. This color mapping is not applied when loading graphs from another source, e.g. networkx.

That said, you can easily configure the `GraphWidget` to apply a similar color mapping by specifying a `set_node_color_mapping`. For example, see the additional color mapping of the [09_type_mapping.ipynb](https://github.com/yWorks/yfiles-jupyter-graphs/blob/main/examples/09_type_mapping.ipynb):

```python
colors = ["#17bebb", "#ffc914", "#0b7189", "#ff6c00", '#76b041']
def custom_node_color_mapping(node: Dict):
    """assign colors based on type"""
    return colors[node['properties']['type']]
w.set_node_color_mapping(custom_node_color_mapping)
```
Of course, in this case, the type happens to be an index which we can use to access a color array. But, in the same fashion, you could map type strings to specific colors and return different colors for different types.

The same happens internally (as default color mapping) when importing a Neo4j graph. In this case, we know that a specific property contains the "type" of the node/relationship, which we cannot assume when importing generic networkx graphs.

**Comment by Analect** [comment]
@fskpf .. thanks for the pointers.

**Comment by fskpf** [comment]
We have released a first version of [yfiles-jupyter-graphs-for-kuzu](https://github.com/yWorks/yfiles-jupyter-graphs-for-kuzu).
